name: Criar Release ZIP

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Determinar nome da versão
      id: version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "tag=build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        fi

    - name: Criar arquivo zip
      run: |
        zip -r projeto.zip . -x '*.git*' '*.github*'

    - name: Criar Release e enviar ZIP
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.version.outputs.tag }}
        tag_name: ${{ steps.version.outputs.tag }}
        files: projeto.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
